server:
  port: 8181
  tomcat:
    max-threads: 1000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 2
    filters: stat,config,wall
    username: root
    url: jdbc:mysql://192.168.1.17:3306/left_pay?characterEncoding=utf-8

